services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:26.4.0

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm', '--features=organization']
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
    volumes:
    - ./target/kommons.jar:/opt/keycloak/providers/kommons.jar
    - ./src/test/resources/:/opt/keycloak/data/import
